### PR TITLE
Update tartube.bat and add tartube_portable.sh for Linux

### PR DESCRIPTION
**Pull request by candrapersada**
you can run Tartube on both 32-bit or 64-bit OS with one bat

### CODE REVIEW

**Comment by candrapersada** [comment]
you can run Tartube on both 32-bit or 64-bit OS with one bat

**Comment by axcore** [comment]
Hi @candrapersada,

I don't know a lot about batch programming. What is the purpose of these changes? Why do you need `tartube_32bit_64bit.bat `?

**Comment by candrapersada** [comment]
> What is the purpose of these changes?

to change the display like this image
aaaaaaaaa

> Why do you need `tartube_32bit_64bit.bat`?


to run tartube on windows 32 or 64 with one `.bat` not two `.bat`

**Comment by axcore** [comment]
I tested these changes, and I think I can't use them.

`install_and_update_tartube.sh`- if users install Tartube with DEB, or RPM, or AUR, or with source code, this will be very confusing, because it won't update the installation. (It will just create a second installation, which is useless). Users who installed Tartube with pip already know how to update it, I think they don't need a shell script.

`echo welcome to Tartube` - this looks nice the first time, then it becomes very annoying. I think most users don't want it

`tartube_32bit_64bit.bat` - I think this is pointless. The Tartube installer contains Msys2 code that works on 64-bit or 32-bit, but not on both. So you can't copy `tartube-portable-64bit.zip` to 32-bit Windows; it won't work.

**Comment by axcore** [comment]
Now, if you modify `Update tartube_32bit_64bit.bat` so it displays python errors (i.e. errors in the mingw window, **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe**), I would definitely use that.

**Pull request closed without merging**
