### PR TITLE
New way to install tartube

### PR DESCRIPTION
**Pull request by candrapersada**
New way to install tartube from MSYS2 for MS Windows

### CODE REVIEW

**Comment by axcore** [comment]
What is the reason for these changes?

**Comment by candrapersada** [comment]
because the latest version of MSYS2 has changed how to install packages.

**Comment by axcore** [comment]
Ok, I will test that.

**Comment by axcore** [comment]
I checked the latest version of MSYS2, `msys2-x86_64-20210215.exe`. Everything is working, so we don't need to change the README.

(Probably MSYS2 was broken, and was fixed quickly.)

**Pull request closed without merging**
